#!/bin/bash

# Replace with your eww build location
if [[ -n $(/home/auri/git/eww/target/release/eww active-windows) ]]; then
    eww close-all
else
    eww open-many music power next disk battery notifications
fi
