#!/bin/bash

# Replace with your eww build location
if [[ -n $(/home/auri/git/eww/target/release/eww active-windows) ]]; then
    /home/auri/git/eww/target/release/eww close-all
else
    /home/auri/git/eww/target/release/eww open-many music power next weather disk resource jellyfren name
fi