#!/bin/bash

## Get data
STATUS="$(playerctl status)"
COVER="images/music.png"
MUSIC_DIR="$HOME/Music"


## Get status
get_status() {
	if [[ $STATUS == *"Playing"* ]]; then
		echo ""
	else
		echo ""
	fi
}

## Get song
get_song() {
	song=`playerctl metadata xesam:title`
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=`playerctl metadata xesam:artist`
	if [[ -z "$artist" ]]; then
		echo ""
	else
		echo "$artist"
	fi	
}

## Get cover
get_cover() {
	echo "images/music.png"
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--cover" ]]; then
	get_cover
fi
