# List of essential tools and applications
# wayland
# pipewire
# xorg-server
# pulseaudio
# pipewire-pulse
# alsa
# pipewire-alsa
# nvidia-drivers
# NetworkManager
# bluez
# blueman
# xfce
# sddm
# hyprland
# eww
# mpd
# ncmpcpp
# dunst
# fuzzel
# kitty
# rofi
# swayidle
# waybar
# swaylock
# swaybg
# wlogout
# wofi
# firefox
# vscodium
# steam
# spotify
# lutris
# heroic-games-launcher
# discord
# prism-launcher
# vlc
# mpv
# ani-cli 
# baobab
# virt-manager
# gimp 
# wine
# waydroid
# audacity
# godot
# mangohud
# gamescope
# gamemode
# obs-studio
# protonup-qt
# protontricks
# winetricks
# vkd3d
# vulkan-tools
# vulkan-icd-loader
# lib32-vulkan-icd-loader
# lib32-gamemode
# lib32-vkd3d
# nwg-look
# qt5ct
# qt6ct
# calibre
# kindle-comic-converter
# scrcpy

# sudo pacman -Syu wayland xorg-server xorg-apps xorg-xwayland pipewire pulseaudio pipewire-pulse pipewire-alsa nvidia NetworkManager lib32-nvidia-utils sddm NetworkManager bluez bluez-utils bluez-deprecated-tools blueman fzf mlocate ttf-liberation otf-font-awesome zsh network-manager-applet xfce sddm hyprland eww mpd build-tools wireplumber ncmpcpp dunst fuzzel kitty rofi swayidle waybar swaylock swaybg wofi firefox lutris heroic-games-launcher discord prism-launcher vlc mpv baobab virt-manager gimp wine winetricks waydroid audacity godot mangohud gamescope gamemode vkd3d vulkan-tools vulkan-icd-loader lib32-vulkan-icd-loader lib32-vulkan-driver lib32-gamemode lib32-vkd3d obs-studio protonup-qt protontricks nwg-look qt5ct qt6ct calibre scrcpy
yay -Sy wayland \
    pipewire \
    xorg-server \
    pipewire \
    pipewire-pulse \
    alsa-utils \
    pipewire-alsa \
    networkmanager \
    bluez \
    bluez-utils \
    blueman xfce4 \
    sddm \
    hyprland-git \
    eww-git \
    mpd \
    ncmpcpp \
    dunst \
    fuzzel \
    kitty \
    rofi \
    swayidle \
    waybar \
    swaylock \
    swaybg \
    wlogout \
    wofi \
    firefox \
    vscodium \
    steam \
    spotify \
    lutris \
    heroic-games-launcher-git \
    discord \
    prismlauncher \
    thefuck \
    zoxide \
    fastfetch \
    eza \
    baobab \
    virt-manager \
    gimp \
    wine \
    waydroid \
    audacity \
    godot \
    mangohud \
    gamescope \
    gamemode \
    obs-studio \
    protonup-qt \
    protontricks \
    winetricks \
    vkd3d \
    vulkan-tools \
    vulkan-icd-loader \
    lib32-gamemode \
    lib32-vulkan-icd-loader \
    lib32-vkd3d \
    nwg-look \
    qt5ct \
    qt6ct \
    calibre \
    scrcpy
