# List of essential tools and applications
# wayland
# pipewire
# x11
# pulseaudio
# pipewire-pulse
# alsa
# pipewire-alsa
# nvidia-drivers
# NetworkManager
# bluez
# blueman
# xfce
# sddm
# hyprland
# eww
# mpd
# ncmpcpp
# dunst
# fuzzel
# kitty
# rofi
# swayidle
# waybar
# swaylock
# swaybg
# wlogout
# wofi
# firefox
# vscodium
# steam
# spotify
# lutris
# heroic-games-launcher
# discord
# prism-launcher
# vlc
# mpv
# ani-cli 
# baobab
# virt-manager
# gimp 
# wine
# waydroid
# audacity
# godot
# mangohud
# gamescope
# gamemode
# obs-studio
# protonup-qt
# protontricks
# winetricks
# nwg-look
# qt5ct
# qt6ct
# calibre
# kindle-comic-converter
# scrcpy

sudo pacman -Syu wayland xorg-server xorg-apps xorg-xwayland pipewire pulseaudio pipewire-pulse alsa pipewire-alsa nvidia NetworkManager lib32-nvidia-utils sddm NetworkManager bluez bluez-utils bluez-deprecated-tools blueman fzf mlocate ttf-liberation otf-font-awesome ttf-ms-fonts ttf-firacode zsh network-manager-applet xfce sddm hyprland eww mpd ncmpcpp dunst fuzzel kitty rofi swayidle waybar swaylock swaybg wlogout wofi firefox vscodium steam spotify lutris heroic-games-launcher discord prism-launcher vlc mpv baobab virt-manager gimp wine winetricks waydroid audacity godot mangohud gamescope gamemode obs-studio protonup-qt protontricks nwg-look qt5ct qt6ct calibre scrcpy
